name: "allowed-routes-api"
description: "Toy API for whitelist testing - matches allowed_routes_remote"
port: 9090

routes:
  # Only the routes that match the whitelist in api_box_config
  - route: "/users"
    methods: ["GET"]
    response: "user_list"

  - route: "/users/<user_id>"
    methods: ["GET"]
    response: "user_detail"

  - route: "/users/<user_id>/profile"
    methods: ["GET"]
    response: "user_profile"

  - route: "/users/<user_id>/posts"
    methods: ["GET"]
    response: "user_posts"

  - route: "/posts"
    methods: ["GET"]
    response: "post_list"

  - route: "/posts/<post_id>"
    methods: ["GET"]
    response: "post_detail"

  - route: "/health"
    methods: ["GET"]
    response: "health_check"

  # Additional routes that should be blocked by api-box whitelist
  - route: "/users/<user_id>/settings"
    methods: ["GET"]
    response: "user_settings"

  - route: "/users/<user_id>/permissions"
    methods: ["GET"]
    response: "user_permissions"

  - route: "/admin"
    methods: ["GET"]
    response: "admin_dashboard"

  - route: "/admin/<admin_id>"
    methods: ["GET"]
    response: "admin_detail"

  - route: "/system/<system_id>/config"
    methods: ["GET"]
    response: "system_config"