name: "allowed-routes-api"
description: "Toy API for whitelist testing - matches allowed_routes_remote"
port: 9090

routes:
  # Only the routes that match the whitelist in api_box_config
  - route: "/users"
    methods: ["GET"]
    response: "user_list"  # List wrapper - keeps legacy for now

  - route: "/users/<user_id>"
    methods: ["GET"]
    response: "core.user"

  - route: "/users/<user_id>/profile"
    methods: ["GET"]
    response: "core.user_profile"

  - route: "/users/<user_id>/posts"
    methods: ["GET"]
    response: "user_posts"  # Composite response - keeps legacy for now

  - route: "/posts"
    methods: ["GET"]
    response: "post_list"  # List wrapper - keeps legacy for now

  - route: "/posts/<post_id>"
    methods: ["GET"]
    response: "core.post"

  - route: "/health"
    methods: ["GET"]
    response: "core.health_check"

  # Additional routes that should be blocked by api-box whitelist
  - route: "/users/<user_id>/settings"
    methods: ["GET"]
    response: "core.user_settings"

  - route: "/users/<user_id>/permissions"
    methods: ["GET"]
    response: "core.user_permissions"

  - route: "/admin"
    methods: ["GET"]
    response: "admin_dashboard"  # Composite response - keeps legacy for now

  - route: "/admin/<admin_id>"
    methods: ["GET"]
    response: "core.admin"

  - route: "/system/<system_id>/config"
    methods: ["GET"]
    response: "core.system_config"