name: test-api-box
description: Test configuration for API Box wrapper with toy remotes - testing restrictions and routes
authors:
  - name: brookie
    email: bguzder-williams@berkeley.edu

remotes:
  - custom_mapping_remote
  - basic_remote
  - restricted_remote
  - allowed_routes_remote
  - versioned_remote

databases:
  - test_db
  - versioned_db

# Non-remote endpoints (API Box's own endpoints)
endpoints:
  - "/"                    # API metadata and information

# Global restrictions (applied to all remotes unless overridden)
restricted:
  - users/{{user_id}}/delete
  - admin/{{admin_id}}/dangerous